### ISSUE TITLE
APIError(code=-2010): Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by korsgaard** [CyberPunkMetalHead/Binance-volatility-trading-bot#24]
For some reason I don't understand yet - it could not sell the 2563 CKBUSDT it bought...  through the binance interface i could only sell 2560 (but in the history it did buy 2563)  ... does that make any sense?
```
CKBUSDT has gained 5.143% in the last 5 minutes, calculating volume in USDT
 preparing to buy 2563 CKBUSDT
TP or SL reached, selling 2563 CKBUSDT...
APIError(code=-2010): Account has insufficient balance for requested action.
```

**Comment by Eugnis** [comment]
Maybe you have 0 BNB on balance?

Btw, in code it was fixed but in last update author removed that https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/commit/1c4455dc062fa13429a82d2b8c1162a0c989b88c#diff-7e6f36133982968f616159a77c6b541c15b502f35e446af9ea5e11c5db1a4aa0R253

**Comment by krczk** [comment]
TP or SL reached, selling 45.5 FETUSDT...
APIError(code=-2010): Account has insufficient balance for requested action

 bot got stucked with selling but i had no problem doing it manual 

(I still some free USD and BNB on spot for fees)

**Comment by CyberPunkMetalHead** [comment]
Bot's been running on my end for several hours without this issue. But I have pushed another update to allow people who have this issue to configure the sell amount for their bot in lines 78-79.
`
# BINANCE cannot always sell all that it buys. Select in % how much to sell
# Set to True to toggle SELL_AMOUNT
CAPPED_SELL = False
SELL_AMOUNT = 99.25`

**Comment by Onions1992** [comment]
Seem to be running into a similar issue:
APIError(code=-2010): Account has insufficient balance for requested action.

This still seems to occur even with latest update to script, any idea what is causing it to fail?

**Comment by Hadiyev** [comment]
The same problem happened while trying to sell 0.467 UMAUSDT. This happened with CAPPED_SELL=False. 
I also got  LOT_SIZE error with when CAPPED_SELL=True.

**Comment by CyberPunkMetalHead** [comment]
I have removed the CAPPED SELL SINCE IT DIDN'T HELP, have pushed (hopefully) a stability fix for the sell function.

**Comment by hExPY** [comment]
Any news on this issue? Guess we have to implement an auto-buy `bnb` feature? What do you think?

**Comment by pawelantczak** [comment]
The approach with ```SELL_AMOUNT = 99.25``` should do the trick, but fee is 1.5%, 0.75% is only when using BNB.

**Comment by Eugnis** [comment]
Better to receive current fee percent from binance with API https://python-binance.readthedocs.io/en/latest/binance.html#binance.client.Client.get_trade_fee

And just calculate it including that fee

**Comment by Onions1992** [comment]
Same issue after updating the current code..

Any ideas how we can overcome this error from happening?

TP or SL reached, selling 39.82 UTKUSDT...
APIError(code=-2010): Account has insufficient balance for requested action.
not enough time has passed yet...
^C

**Comment by djhashh** [comment]
can we sell on different exchange? also..what about triangular arbitrage for profits

**Comment by qing666888** [comment]
How we can solve this error？
APIError(code=-2010): Account has insufficient balance for requested action.

**Comment by cweiner20** [comment]
I was just able to resolve it and sell a coin. It seems as though the Capped_Sell and Sell_Amount have been removed from the current code. Look at @Eugnis comment from 3 days ago: https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/issues/24#issuecomment-836887498 and replace the green code in yours. Lines 252-257 and 260-263 should be replaced.

**Comment by cweiner20** [comment]
> I was just able to resolve it and sell a coin. It seems as though the Capped_Sell and Sell_Amount have been removed from the current code. Look at @Eugnis comment from 3 days ago: [#24 (comment)](https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/issues/24#issuecomment-836887498) and replace the green code in yours. Lines 252-257 and 260-263 should be replaced.



> How we can solve this error？
> APIError(code=-2010): Account has insufficient balance for requested action.

I was just able to resolve it and sell a coin. It seems as though the Capped_Sell and Sell_Amount have been removed from the current code. Look at @Eugnis comment from 3 days ago: https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/issues/24#issuecomment-836887498 and replace the green code in yours. Lines 252-257 and 260-263 should be replaced.

**Comment by qing666888** [comment]
> > How we can solve this error？
> > APIError(code=-2010): Account has insufficient balance for requested action.
> 
> I was just able to resolve it and sell a coin. It seems as though the Capped_Sell and Sell_Amount have been removed from the current code. Look at @Eugnis comment from 3 days ago: [#24 (comment)](https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/issues/24#issuecomment-836887498) and replace the green code in yours. Lines 252-257 and 260-263 should be replaced.

"pay fees in BNB "  enabled or disabled?

**Comment by cweiner20** [comment]
> > > How we can solve this error？
> > > APIError(code=-2010): Account has insufficient balance for requested action.
> > 
> > 
> > I was just able to resolve it and sell a coin. It seems as though the Capped_Sell and Sell_Amount have been removed from the current code. Look at @Eugnis comment from 3 days ago: [#24 (comment)](https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/issues/24#issuecomment-836887498) and replace the green code in yours. Lines 252-257 and 260-263 should be replaced.
> 
> "pay fees in BNB " enabled or disabled?

enabled with bnb funds in account.

**Comment by zkrige** [comment]
I've got bnb funds in account and this flag enabled - still get the error
I've also turned off "pay fees in bnb" and I still get the error

**Comment by zkrige** [comment]
ok so. I had to add the CAPPED_SELL code back and it seems to work better. not 100% tho - am still getting `Filter failure: LOT_SIZE`

**Comment by rodrigogs** [comment]
This is annoying, I cant figure it out :/

**Comment by rodrigogs** [comment]
Fixed, you just need to have some BNB

**Comment by iamraffe** [comment]
This is still happening, I have plenty of BNB in my account.

**Comment by cweiner20** [comment]
> This is still happening, I have plenty of BNB in my account.

@iamraffe, do you have USDT in your account too?

**Comment by iamraffe** [comment]
Yep. I added back the code from one of the comments above and was able to sell some of the coins, not having a LOT_SIZE error and looking into it.
